### PR TITLE
Njb/init auth enhancements data component

### PR DESCRIPTION
**Pull request by NickBolles**
See #178

### CODE REVIEW

**Comment by NickBolles** [comment]
I need to fix this quick, I forgot I merged master to it

**Comment by NickBolles** [comment]
There we go, @marshallswain this should be ready to merge to the data-component branch

**Comment by NickBolles** [comment]
@marshallswain should we close this PR then?

**Comment by marshallswain** [comment]
Ah. Yes.  Sorry I forgot to update you.  I know your time is valuable, and I apologize.

**Pull request closed without merging**
