### PR TITLE
Improve get action & updateItem mutation

### PR DESCRIPTION
**Pull request by beeplin**
Add option `skipRequestIfExists` for get action: if the record already exists in store, skip the remote request. #42

Add option `upsert` for enhanced updateItem mutation: add new records pushed by 'updated/patched' socketio events into store, instead of discarding them. #110

### CODE REVIEW

**Comment by marshallswain** [comment]
@beeplin this looks beautiful.  I feel like the default for `upsert` should be `true`, since people would expect it to be created, anyway.  Do you have any thoughts against it?

**Comment by marshallswain** [comment]
What do you feel about 

`upsert` —> `addOnUpsert`

`skipRequestIfExists` —> `localOnly`

???

**Comment by marshallswain** [comment]
Also, let’s definitely set upsert to true by default. This is technically a bug fix, since the code was intended to work this way, but I messed up the mutation.

**Comment by beeplin** [comment]
`localOnly` might be a little bit confusing, because if the record is not in state, there will still be a remote request, which does not sound like `localOnly` literally.

`addOnUpsert` sounds great~

**Comment by marshallswain** [comment]
@beeplin Please let me know when this is ready to merge.

**Comment by beeplin** [comment]
Sorry has  been busy this week. only 2 things left for this PR: rename the two new params, and write tests for the new get actions (yet to learn how).

I am afraid I would have no enough spare time to complete it until next Wenesday.  Is it troubling your schedule for the new release?

**Comment by marshallswain** [comment]
Everything is fine. I’m working on documentation for a while, anyway.
Thanks!

**Comment by marshallswain** [comment]
Released as part of `feathers-vuex@1.2.0`

**Pull request merged**
