### PR TITLE
Add feathersClient argument on initAuth to set JWT

### PR DESCRIPTION
**Pull request by NickBolles**
### Summary
- [x ] Tell us about the problem your pull request is solving.
#106 (and possibly #97 #78 and #93 #8)
- [X ] Are there any open issues that are related to this?
- [ ] Is this PR dependent on PRs in other repos?

### Other Information
Docs PR to come

### CODE REVIEW

**Comment by marshallswain** [comment]
@NickBolles Thanks for this solution!  Could you also open the same PR against the `data-component` branch?  I have a huge number of updates that I'm about to merge to master and it would make it much easier for me to not lose this feature in the process.

**Comment by NickBolles** [comment]
@marshallswain nice, yea I can do that later tonight

**Comment by NickBolles** [comment]
@marshallswain There aren't any conflicts, except for the unit tests, which I just changed to use a promise instead of a done callback. You should be fine merging your changes, and I can merge master into this PR branch, then merge to master

**Comment by marshallswain** [comment]
Conflicts weren't many, so I've merged this.  This is published as `feathers-vuex@1.7.0-pre.46`.  Thanks, @NickBolles !

**Comment by NickBolles** [comment]
@marshallswain I made an issue on the docs repo to update docs when I'm done with my prs. I think I'm gonna submit one for typescript defs later tonight.

**Pull request merged**
