### PR TITLE
Use merge for toJson object

### LINKED ISSUE #196: Basic usage breaks in Nuxt SSR
FeathersVuex breaks on Nuxt SSR with the most basic usage.

`$FeathersVuex.Todo` items load fine on client side (open root, then click the link to `/todos`);

On server side (refresh `/todos`), infinite recursion happens in `toJSON` in `feathers-vuex/lib/service-module/model.js:237`.

### Steps to reproduce

See this repo/branch for a reproduction:
https://github.com/Palivonas/feathers-vuex-bug-reproduction/tree/models-tojson-nuxt-ssr

FeathersVuex `1.7.0-pre.54`.
Node 10 and 8 tested, app created using `create-nuxt-app`.

### PR DESCRIPTION
**Pull request by NickBolles**
This will avoid infinite recursion with circular references

### Summary
- [x] Tell us about the problem your pull request is solving.
#196 - infinite recursion when there are circular references
- [x] Are there any open issues that are related to this?
closes #196, caused by #179 
- [x] Is this PR dependent on PRs in other repos?
caused by #179 

#### Question
- Is merge the best route here? it's probably the easiest, but maybe not the most performant  if we already know the key we want to copy to the json object.
- Should we use merge for `cloneWithAccessors`?

### CODE REVIEW

**Comment by NickBolles** [comment]
@marshallswain could you take a look at my questions in this? 

@Palivonas this passes your reproduction repo, are there any other test cases to do?

**Comment by marshallswain** [comment]
I’ll bet this won’t work with getters whicj have no setter.

**Comment by NickBolles** [comment]
@marshallswain if they are enumerable it should work, check this code sample, the last output is the most relevant

https://runkit.com/nickbolles/lodash-merge-and-defineproperties

**Comment by marshallswain** [comment]
@NickBolles It seems to me like lodash.merge works exactly the same as copyWithAccessors.  Thanks for setting up that runkit.

**Comment by marshallswain** [comment]
Published as `feathers-vuex@1.7.0-pre.56`

**Comment by NickBolles** [comment]
@marshallswain NP! 

So do we need to add any documentation to the instance defaults (or anything else) to make sure that getters are enumerable if you want the property serialized to JSON (such as when SSR and sending it to the client). #196 is a good example that we could point to the documentation.

**Comment by marshallswain** [comment]
@NickBolles Yeah.  Feel free to make a note in the /docs repo.

**Pull request merged**
